version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: webhook_postgres
    environment:
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_password
      POSTGRES_DB: webhook_payments
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhook_user -d webhook_payments"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - webhook_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: webhook_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@webhook.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - webhook_network
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

networks:
  webhook_network:
    driver: bridge
